# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sylvia van Os
description: "Hello, I'm Sylvia. I like to hack on things."
subtitle: 'In my spare time I love to contribute to <abbr title="AKA: Open Source">Free Software</abbr>, play video games and listen to music (primarily Metal and Electronic).'
main_links:
  - name: GitHub
    url: https://github.com/TheLastProject
  - name: Blog
    url: /blog
    feed: /feed.xml
  - name: Mastodon
    url: https://chaos.social/@SylvieLorxu
home:
  presentations:
    - name: Open Source 101
      date: July 2019
      url: https://vimeo.com/346198962
  projects:
    - name: Catima
      description: An Android app to manage loyalty cards with.
      github:
        repo: TheLastProject/Catima
      android:
        package: me.hackerchick.catima
    - name: Raise To Answer
      description: Simply hold your phone to your ear to answer an incoming phone call. Or flip it upside down to decline. 
      github:
        repo: TheLastProject/RaiseToAnswer
      android:
        package: me.hackerchick.raisetoanswer
  articles:
    - title: "F-Droid (featuring Sylvia van Os & Hans-Christoph Steiner!) | Foss & Crafts"
      url: https://fossandcrafts.org/episodes/057-f-droid.html
      author: FOSS & Crafts
      subject: F-Droid
      date: 2023-05-14
      description: interview on a project I used to contribute to
    - title: "Die digitale Brieftasche | c’t uplink 46.7"
      url: https://www.youtube.com/watch?v=0CjAPZ_IWVA&t=1537s
      author: Heise
      subject: Catima
      date: 2023-01-21
      description: german podcast positively reviewing Catima
    - title: "Die digitale Brieftasche | c't 03/2023"
      url: https://shop.heise.de/ct-03-2023/PDF
      author: Heise
      subject: Catima
      date: 2023-01-14
      description: magazine contains positive review of Catima and icon on cover
    - title: "Pext: new and improved AppImage"
      url: https://assassinate-you.net/posts/2018/10/pext-new-improved-appimage/
      author: TheAssassin
      subject: Pext
      date: 2018-10-08
    - title: "Pext: Python Extendable Tool"
      url: https://news.ycombinator.com/item?id=17772460
      author: Hacker News
      subject: Pext
      date: 2018-08-17
      description: reached frontpage and caused Pext to reach GitHub Daily Trending
    - title: Pext is an extendable Python-based tool that's a little hard to explain…
      url: http://www.omgubuntu.co.uk/2017/03/pext-python-extendable-tool
      author: OMGUbuntu
      subject: Pext
      date: 2017-03-30
    - title: How to Use Pass, the Ultimate Open-Source Password Manager
      url: http://www.makeuseof.com/tag/use-pass-ultimate-open-source-password-manager/
      author: MakeUseOf
      subject: Pext
      date: 2016-08-23
      description: see bottom of page
  contacts:
    - service: Matrix
      url: https://matrix.to/#/@SylvieLorxu:matrix.org
      username: "@SylvieLorxu:matrix.org"
      keys:
        - id: VEKGLGYNHI
          fields:
            Key: <code>ic/q z4bH EsSZ DHzR z1X2 GS8e +HVX lnDJ 7p2S wU+W Tfw</code>
            Type: Laptop (Fedora)
        - id: BYIVUCWLNG
          fields:
            Key: <code>3cQZ zVuR FBoN ln/1 R2HN TeQR Fqom xq88 g3rw tr/P my0</code>
            Type: Phone (Fairphone 3)
    - service: Telegram
      url: https://t.me/lorxu
      username: Lorxu
    - service: Email (randomly generated name for anti-spam)
      url: mailto:web.qvyny@sylviavanos.nl
      username: web.qvyny@sylviavanos.nl

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
# The eollowing items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
